In [16]:
import numpy as np
a = [True, False, True, True]
a_mt = np.asmatrix(a)
aa = a_mt.reshape(2,2)

b = [True,True,True,False]
b_mt = np.asmatrix(b)
bb = b_mt.reshape(2,2)

In [17]:
aa

matrix([[ True, False],
        [ True,  True]])

In [18]:
bb

matrix([[ True,  True],
        [ True, False]])

In [20]:
np.all(aa|bb, axis = 0)

matrix([[ True,  True]])