In [1]:
#########
# imports
#########
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

In [4]:
#########
# Loading the data
#########
data_file = "Data\\"
data_name = "train.csv"

idx = np.genfromtxt(data_file + data_name, delimiter=",", skip_header = 1, usecols=[0])
y = np.genfromtxt(data_file + data_name, delimiter=",", dtype=str, skip_header = 1, usecols=[1], converters={1:lambda x: 0 if x == b'b' else 1})
tx = np.genfromtxt(data_file + data_name, delimiter=",", skip_header = 1, usecols = list(range(2,32)))

In [11]:
import pandas as pd
df = pd.read_csv(data_file + data_name)
df.columns[2:].values == 'PRI_jet_num'
# this is the original input. after deleting relating columns, 22 becomes 18 (delete col 5, 6, 12, 21 ahead of 22)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False])

In [13]:
def remove_related_features(tx):
    del_features = [5, 6, 12, 21, 24, 25, 26, 27, 28, 29]
    tx = np.delete(tx, del_features, 1)
    return tx
tx_remove = remove_related_features(tx)
pd.DataFrame(tx_remove)

0        1        2       3       4        5        6      7   \
0       138.470   51.655   97.827  27.980    0.91  124.711    2.666  3.064   
1       160.937   68.768  103.235  48.146 -999.00 -999.000 -999.000  3.473   
2      -999.000  162.172  125.953  35.635 -999.00 -999.000 -999.000  3.148   
3       143.905   81.417   80.943   0.414 -999.00 -999.000 -999.000  3.310   
4       175.864   16.915  134.805  16.405 -999.00 -999.000 -999.000  3.891   
...         ...      ...      ...     ...     ...      ...      ...    ...   
249995 -999.000   71.989   36.548   5.042 -999.00 -999.000 -999.000  1.392   
249996 -999.000   58.179   68.083  22.439 -999.00 -999.000 -999.000  2.585   
249997  105.457   60.526   75.839  39.757 -999.00 -999.000 -999.000  2.390   
249998   94.951   19.362   68.812  13.504 -999.00 -999.000 -999.000  3.365   
249999 -999.000   72.756   70.831   7.479 -999.00 -999.000 -999.000  2.025   

            8        9   ...     20       21   22       23       24       25  \
0       41.928  197.760  ... -0.277  258.733  2.0   67.435    2.150    0.444   
1        2.078  125.157  ... -1.916  164.546  1.0   46.226    0.725    1.158   
2        9.336  197.814  ... -2.186  260.414  1.0   44.251    2.053   -2.028   
3        0.414   75.968  ...  0.060   86.062  0.0 -999.000 -999.000 -999.000   
4       16.405   57.983  ... -0.871   53.131  0.0 -999.000 -999.000 -999.000   
...        ...      ...  ...    ...      ...  ...      ...      ...      ...   
249995   5.042   55.892  ...  2.859  144.665  0.0 -999.000 -999.000 -999.000   
249996  22.439   50.618  ... -0.867   80.408  0.0 -999.000 -999.000 -999.000   
249997  22.183  120.462  ... -2.890  198.907  1.0   41.992    1.800   -0.166   
249998  13.504   55.859  ...  0.811  112.718  0.0 -999.000 -999.000 -999.000   
249999   7.479   83.240  ... -1.596   99.405  0.0 -999.000 -999.000 -999.000   

             26      27       28       29  
0        46.062    1.24   -2.475  113.497  
1      -999.000 -999.00 -999.000   46.226  
2      -999.000 -999.00 -999.000   44.251  
3      -999.000 -999.00 -999.000    0.000  
4      -999.000 -999.00 -999.000    0.000  
...         ...     ...      ...      ...  
249995 -999.000 -999.00 -999.000    0.000  
249996 -999.000 -999.00 -999.000    0.000  
249997 -999.000 -999.00 -999.000   41.992  
249998 -999.000 -999.00 -999.000    0.000  
249999 -999.000 -999.00 -999.000    0.000  

[250000 rows x 30 columns]

In [3]:
#########
# Defining the loss functions
#########
def compute_loss(y, tx, w):

    """Calculate the loss using either MSE or MAE.

    Args:
        y: numpy array of shape=(N, )
        tx: numpy array of shape=(N,D)
        w: numpy array of shape=(D,). The vector of model parameters.

    Returns:
        the value of the loss (a scalar), corresponding to the input parameters w.
    """
    e = y - np.matmul(tx, w)
    te = np.transpose(e)
    N = len(y)
    return (np.matmul(te, e) / (2 * N))

def compute_loss_mae(y, tx, w):
    e = y - np.matmul(tx, w)
    N = len(y)
    return np.mean(np.abs(e))

In [110]:
##########
# Linear Gradient Descent
##########
def compute_gradient(y, tx, w):
    """Computes the gradient at w.
        
    Args:
        y: numpy array of shape=(N, )
        tx: numpy array of shape=(N, D)
        w: numpy array of shape=(D, ). The vector of model parameters.
        
    Returns:
        An numpy array of shape (D, ) (same shape as w), containing the gradient of the loss at w.
    """
    e = y - np.matmul(tx, w)
    N = len(y)
    return np.matmul(tx.transpose(), e) * (-1) / N

def least_squares_GD(y, tx, initial_w, max_iters, gamma):
    """The Gradient Descent (GD) algorithm.
        
    Args:
        y: numpy array of shape=(N, )
        tx: numpy array of shape=(N,D)
        initial_w: numpy array of shape=(D, ). The initial guess (or the initialization) for the model parameters
        max_iters: a scalar denoting the total number of iterations of GD
        gamma: a scalar denoting the stepsize
        
    Returns:
        w: final optimized parameter w of shape(D, )
        loss: final loss (scalar) at max_iter with final optimized parameter w
    """
    # Define parameters to store w and loss
    w = initial_w
    for n_iter in range(max_iters):
        gradient = compute_gradient(y, tx, w)
        w = w - gamma * gradient
    loss = compute_loss(y, tx, w)
    return w, loss

In [5]:
#################
# Stochastic Gradient Descent
#################
def batch_iter(y, tx, batch_size, num_batches=1, shuffle=True):
    """
    Generate a minibatch iterator for a dataset.
    Takes as input two iterables (here the output desired values 'y' and the input data 'tx')
    Outputs an iterator which gives mini-batches of `batch_size` matching elements from `y` and `tx`.
    Data can be randomly shuffled to avoid ordering in the original data messing with the randomness of the minibatches.
    Example of use :
    for minibatch_y, minibatch_tx in batch_iter(y, tx, 32):
        <DO-SOMETHING>
    """
    data_size = len(y)

    if shuffle:
        shuffle_indices = np.random.permutation(np.arange(data_size))
        shuffled_y = y[shuffle_indices]
        shuffled_tx = tx[shuffle_indices]
    else:
        shuffled_y = y
        shuffled_tx = tx
    for batch_num in range(num_batches):
        start_index = batch_num * batch_size
        end_index = min((batch_num + 1) * batch_size, data_size)
        if start_index != end_index:
            yield shuffled_y[start_index:end_index], shuffled_tx[start_index:end_index]

def compute_stoch_gradient(y, tx, w): 
    """Compute a stochastic gradient at w from just few examples n and their corresponding y_n labels.
        
    Args:
        y: numpy array of shape=(batch_size=1, )
        tx: numpy array of shape=(batch_size=1, D)
        w: numpy array of shape=(D, ). The vector of model parameters.
        
    Returns:
        A numpy array of shape (D, ) (same shape as w), containing the stochastic gradient of the loss at w.
    """
    
    batch_size = len(y)
    e = y - np.matmul(tx, w)
    return np.matmul(tx.transpose(), e) * (-1) / batch_size


def stochastic_gradient_descent(y, tx, initial_w, batch_size, max_iters, gamma):
    """The Stochastic Gradient Descent algorithm (SGD).
            
    Args:
        y: numpy array of shape=(N, )
        tx: numpy array of shape=(N,D)
        initial_w: numpy array of shape=(D, ). The initial guess (or the initialization) for the model parameters
        batch_size: a scalar denoting the number of data points in a mini-batch used for computing the stochastic gradient
        max_iters: a scalar denoting the total number of iterations of SGD
        gamma: a scalar denoting the stepsize
        
    Returns:
        w: final optimized parameter w of shape(D, ) (using SGD)
        loss: final loss (scalar) at max_iter with final optimized parameter w (using SGD)
    """

    w = initial_w
    for n_iter in range(max_iters):
        for minibatch_y, minibatch_tx in batch_iter(y, tx, batch_size = batch_size): # there is only one batch actually.
            gradient = compute_stoch_gradient(minibatch_y, minibatch_tx, w)
        w = w - gamma * gradient
    loss = compute_loss(y, tx, w)
    return w, loss

In [6]:
##############
# Least square regression using normal equations
##############
def least_squares(y, tx):
    """Calculate the least squares solution.
       returns mse, and optimal weights.
    
    Args:
        y: numpy array of shape (N,), N is the number of samples.
        tx: numpy array of shape (N,D), D is the number of features.
    
    Returns:
        w: optimal weights, numpy array of shape(D,), D is the number of features.
        mse: scalar.

    >>> least_squares(np.array([0.1,0.2]), np.array([[2.3, 3.2], [1., 0.1]]))
    (array([ 0.21212121, -0.12121212]), 8.666684749742561e-33)
    """
    XTX = tx.transpose() @ tx
    XTy = tx.transpose() @ y
    w = np.linalg.solve(XTX, XTy)
    mse = compute_loss(y, tx, w)
    return w, mse

In [7]:
################
# Ridge regression
################
def ridge_regression(y, tx, lambda_):
    """implement ridge regression.
    
    Args:
        y: numpy array of shape (N,), N is the number of samples.
        tx: numpy array of shape (N,D), D is the number of features.
        lambda_: scalar.
    
    Returns:
        w: optimal weights, numpy array of shape(D,), D is the number of features.

    >>> ridge_regression(np.array([0.1,0.2]), np.array([[2.3, 3.2], [1., 0.1]]), 0)
    array([ 0.21212121, -0.12121212])
    >>> ridge_regression(np.array([0.1,0.2]), np.array([[2.3, 3.2], [1., 0.1]]), 1)
    array([0.03947092, 0.00319628])
    """
    N = len(y)
    D = tx.shape[1]

    # Generating the diagnoal matrix lambda' * I (D * D) = Lambda_slash
    lambda_slash = 2 * lambda_ * N
    Lambda_slash = np.diag(lambda_slash * np.ones(D))

    Coef = (tx.transpose() @ tx) + Lambda_slash
    w_star = np.linalg.inv(Coef) @ tx.transpose() @ y
    loss = compute_loss(y, tx, w_star)
    return w_star, loss

### logistic regression with gradient descent

In [ ]:
####################
# Logistic regression 
####################
def sigmoid(t):
    """apply sigmoid function on t.

    Args:
        t: scalar or numpy array

    Returns:
        scalar or numpy array

    >>> sigmoid(np.array([0.1]))
    array([0.52497919])
    >>> sigmoid(np.array([0.1, 0.1]))
    array([0.52497919, 0.52497919])
    """
    e_pow = np.exp(t)
    return e_pow / (1 + e_pow)

# Note this is different from compute_loss from previous content
def calculate_loss(y, tx, w):
    """compute the cost by negative log likelihood.

    Args:
        y:  shape=(N, 1)
        tx: shape=(N, D)
        w:  shape=(D, 1) 

    Returns:
        a non-negative loss

    >>> y = np.c_[[0., 1.]]
    >>> tx = np.arange(4).reshape(2, 2)
    >>> w = np.c_[[2., 3.]]
    >>> round(calculate_loss(y, tx, w), 8)
    1.52429481
    """
    
    assert y.shape[0] == tx.shape[0]
    assert tx.shape[1] == w.shape[0]
 
    N = y.shape[0]
    res = 0
    for n in range(0, N):
        xnt_w = tx[n].transpose() @ w
        res += np.log(1 + np.exp(xnt_w)) - y[n] * xnt_w
    res = res / N
    return res[0]

# Note this is different from the compute_gradient in the previous content.
def calculate_gradient(y, tx, w):
    """compute the gradient of loss.
    
    Args:
        y:  shape=(N, 1)
        tx: shape=(N, D)
        w:  shape=(D, 1) 

    Returns:
        a vector of shape (D, 1)

    >>> np.set_printoptions(8)
    >>> y = np.c_[[0., 1.]]
    >>> tx = np.arange(6).reshape(2, 3)
    >>> w = np.array([[0.1], [0.2], [0.3]])
    >>> calculate_gradient(y, tx, w)
    array([[-0.10370763],
           [ 0.2067104 ],
           [ 0.51712843]])
    """
    N = y.shape[0]
    return (tx.transpose() @ (sigmoid(tx @ w) - y)) / N

def learning_by_gradient_descent(y, tx, w, gamma):
    """
    Do one step of gradient descent using logistic regression. Return the loss and the updated w.

    Args:
        y:  shape=(N, 1)
        tx: shape=(N, D)
        w:  shape=(D, 1) 
        gamma: float

    Returns:
        loss: scalar number
        w: shape=(D, 1) 

    >>> y = np.c_[[0., 1.]]
    >>> tx = np.arange(6).reshape(2, 3)
    >>> w = np.array([[0.1], [0.2], [0.3]])
    >>> gamma = 0.1
    >>> loss, w = learning_by_gradient_descent(y, tx, w, gamma)
    >>> round(loss, 8)
    0.62137268
    >>> w
    array([[0.11037076],
           [0.17932896],
           [0.24828716]])
    """
    w_descent = w - gamma * calculate_gradient(y, tx, w)
    loss = calculate_loss(y, tx, w) # we are here calculating the loss corresponding the w before update.
    return loss, w_descent

def logistic_regression_gradient_descent(y, x):
    # init parameters
    max_iter = 10000
    threshold = 1e-8
    gamma = 0.5
    losses = []

    # build tx
    tx = np.c_[np.ones((y.shape[0], 1)), x]
    w = np.zeros((tx.shape[1], 1))

    # start the logistic regression
    for iter in range(max_iter):
        # get loss and update w.
        loss, w = learning_by_gradient_descent(y, tx, w, gamma)
        # converge criterion
        losses.append(loss)
        if len(losses) > 1 and np.abs(losses[-1] - losses[-2]) < threshold:
            break
    return w, loss[-1]


### regularized logistic regression

In [8]:
def penalized_logistic_regression(y, tx, w, lambda_):
    """return the loss and gradient.

    Args:
        y:  shape=(N, 1)
        tx: shape=(N, D)
        w:  shape=(D, 1)
        lambda_: scalar

    Returns:
        loss: scalar number
        gradient: shape=(D, 1)

    >>> y = np.c_[[0., 1.]]
    >>> tx = np.arange(6).reshape(2, 3)
    >>> w = np.array([[0.1], [0.2], [0.3]])
    >>> lambda_ = 0.1
    >>> loss, gradient = penalized_logistic_regression(y, tx, w, lambda_)
    >>> round(loss, 8)
    0.63537268
    >>> gradient 
    array([[-0.08370763],
           [ 0.2467104 ],
           [ 0.57712843]])
    """
    loss_penalized = calculate_loss(y, tx, w) + lambda_ * (w.transpose() @ w)[0][0]
    gradient_penalized = calculate_gradient(y, tx, w) + (2 * lambda_ * w)
    return loss_penalized, gradient_penalized

def learning_by_penalized_gradient(y, tx, w, gamma, lambda_):
    """
    Do one step of gradient descent, using the penalized logistic regression.
    Return the loss and updated w.

    Args:
        y:  shape=(N, 1)
        tx: shape=(N, D)
        w:  shape=(D, 1)
        gamma: scalar
        lambda_: scalar

    Returns:
        loss: scalar number
        w: shape=(D, 1)

    >>> np.set_printoptions(8)
    >>> y = np.c_[[0., 1.]]
    >>> tx = np.arange(6).reshape(2, 3)
    >>> w = np.array([[0.1], [0.2], [0.3]])
    >>> lambda_ = 0.1
    >>> gamma = 0.1
    >>> loss, w = learning_by_penalized_gradient(y, tx, w, gamma, lambda_)
    >>> round(loss, 8)
    0.63537268
    >>> w
    array([[0.10837076],
           [0.17532896],
           [0.24228716]])
    """
    loss, gradient = penalized_logistic_regression(y, tx, w, lambda_)
    w = w - gamma * gradient
    return loss, w

def logistic_regression_penalized_gradient_descent_demo(y, x):
    # init parameters
    max_iter = 10000
    gamma = 0.5
    lambda_ = 0.0005
    threshold = 1e-8
    losses = []

    # build tx
    tx = np.c_[np.ones((y.shape[0], 1)), x]
    w = np.zeros((tx.shape[1], 1))

    # start the logistic regression
    for iter in range(max_iter):
        # get loss and update w.
        loss, w = learning_by_penalized_gradient(y, tx, w, gamma, lambda_)
        # log info
        losses.append(loss)
        if len(losses) > 1 and np.abs(losses[-1] - losses[-2]) < threshold:
            break
    return w, loss[-1]